openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Axie'
  license:
    name: MIT
servers:
  - url: 'https://axie.postman.com'
paths:
  /axies/{id}:
    get:
      summary: 'Returns a single Axie'
      operationId: listAxie
      tags:
        - axies
      parameters:
        - name: id
          in: path
          description: ID of the Axie
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Details about a Axie by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Axie'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /axies:
    get:
      summary: 'Returns all Axies'
      operationId: listAxies
      tags:
        - axies
      responses:
        '200':
          description: 'Details about Axies'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Axie'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Axie:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []