openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Pokemon API'
  license:
    name: MIT
servers:
  - url: 'https://pokemon.postman.com'
paths:
  /pokemons/{id}:
    get:
      summary: 'Returns a single Pokemon'
      operationId: listPokemon
      tags:
        - pokemons
      parameters:
        - name: id
          in: path
          description: ID of the Pokemon
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Details about a Pokemon by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pokemons:
    get:
      summary: 'Returns all Pokemons'
      operationId: listPokemons
      tags:
        - pokemons
      responses:
        '200':
          description: 'Details about Pokemons'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pokemon'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pokemon:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
